INSERT INTO CODE_MASTER VALUES ('C01', 'gender', '성별');
INSERT INTO CODE_MASTER VALUES ('C02', 'visit', '환자방문 상태');
INSERT INTO CODE_MASTER VALUES ('C03', 'medical', '진료과목');
INSERT INTO CODE_MASTER VALUES ('C04', 'stage', '진료 유형');


INSERT INTO CODE VALUES ('C01', 'M', '남');
INSERT INTO CODE VALUES ('C01', 'F', '여');
INSERT INTO CODE VALUES ('C02', 'V', '방문중');
INSERT INTO CODE VALUES ('C02', 'E', '종료');
INSERT INTO CODE VALUES ('C02', 'C', '취소');
INSERT INTO CODE VALUES ('C03', '01', '내과');
INSERT INTO CODE VALUES ('C03', '02', '안과');
INSERT INTO CODE VALUES ('C03', '03', '소아과');
INSERT INTO CODE VALUES ('C03', '04', '비뇨기과');
INSERT INTO CODE VALUES ('C03', '05', '외과');
INSERT INTO CODE VALUES ('C04', 'W', '자가격리');
INSERT INTO CODE VALUES ('C04', 'D', '약처방');
INSERT INTO CODE VALUES ('C04', 'T', '검사');
