DROP TABLE CODE IF EXISTS;
DROP TABLE CODE_MASTER IF EXISTS;


CREATE TABLE CODE_MASTER (
 code_group     VARCHAR(10) NOT NULL PRIMARY KEY,
 code_group_name VARCHAR(10) NOT NULL,
 description    VARCHAR(10) NOT NULL
);

CREATE TABLE CODE (
 code_group     VARCHAR(10) NOT NULL,
 code           VARCHAR(10) NOT NULL PRIMARY KEY,
 code_name      VARCHAR(10) NOT NULL
);
ALTER TABLE CODE ADD CONSTRAINT fk_code_group FOREIGN KEY (code_group) REFERENCES CODE_MASTER (code_group);

